export enum ApplicationStatus {
  UNVERIFIED = "UNVERIFIED",
  VERIFIED = "INCOMPLETE",
  APPLIED = "APPLIED",
  ADMITTED = "ADMITTED",
  REJECTED = "REJECTED",
  DECLINED = "DECLINED",
  CONFIRMED = "CONFIRMED"
}
