export enum DispatchActionType {
  AUTH_REGISTER = "AUTH_REGISTER",
  AUTH_LOGIN = "AUTH_LOGIN",
  AUTH_LOGIN_TOKEN = "AUTH_LOGIN_TOKEN",
  AUTH_VERIFY = "AUTH_VERIFY",
  SPONSORS_LIST = "SPONSORS_LIST",
  APPLICATION_UPLOAD_RESUME = "APPLICATION_UPLOAD_RESUME"
}
